// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RegistroCreditos.Api.Data;

#nullable disable

namespace RegistroCreditos.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260827041932_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RegistroCreditos.Api.Models.Credito", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CedulaCliente")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ComercialNombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NombreCliente")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("PlazoMeses")
                        .HasColumnType("integer");

                    b.Property<decimal>("TasaInteres")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.Property<decimal>("ValorCredito")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CedulaCliente");

                    b.HasIndex("ComercialNombre");

                    b.HasIndex("FechaRegistro");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Creditos");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CedulaCliente = "1000000001",
                            ComercialNombre = "Sede Norte",
                            FechaRegistro = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            NombreCliente = "Pepito Perez",
                            PlazoMeses = 10,
                            TasaInteres = 2m,
                            UsuarioId = 1,
                            ValorCredito = 7800000m
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            CedulaCliente = "1000000002",
                            ComercialNombre = "Sede Sur",
                            FechaRegistro = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            NombreCliente = "Maria Perez",
                            PlazoMeses = 5,
                            TasaInteres = 2m,
                            UsuarioId = 1,
                            ValorCredito = 12500000m
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            CedulaCliente = "1000000003",
                            ComercialNombre = "Sede Centro",
                            FechaRegistro = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            NombreCliente = "Antonio Rodriguez",
                            PlazoMeses = 5,
                            TasaInteres = 2m,
                            UsuarioId = 1,
                            ValorCredito = 10312673m
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            CedulaCliente = "1000000004",
                            ComercialNombre = "Sede Este",
                            FechaRegistro = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            NombreCliente = "Giselle López",
                            PlazoMeses = 12,
                            TasaInteres = 2m,
                            UsuarioId = 1,
                            ValorCredito = 8628510m
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            CedulaCliente = "1000000005",
                            ComercialNombre = "Sede Oeste",
                            FechaRegistro = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            NombreCliente = "Martha Perez",
                            PlazoMeses = 24,
                            TasaInteres = 2m,
                            UsuarioId = 1,
                            ValorCredito = 5889085m
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            CedulaCliente = "1000000006",
                            ComercialNombre = "Sede Norte",
                            FechaRegistro = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            NombreCliente = "Isaac llanos",
                            PlazoMeses = 48,
                            TasaInteres = 2m,
                            UsuarioId = 1,
                            ValorCredito = 14793565m
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777777"),
                            CedulaCliente = "1000000007",
                            ComercialNombre = "Sede Sur",
                            FechaRegistro = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            NombreCliente = "Teresa Gutierrez",
                            PlazoMeses = 50,
                            TasaInteres = 2m,
                            UsuarioId = 1,
                            ValorCredito = 8072348m
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888888"),
                            CedulaCliente = "1000000008",
                            ComercialNombre = "Sede Centro",
                            FechaRegistro = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            NombreCliente = "Isabel Llanos",
                            PlazoMeses = 60,
                            TasaInteres = 2m,
                            UsuarioId = 1,
                            ValorCredito = 5143860m
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999999999999"),
                            CedulaCliente = "1000000009",
                            ComercialNombre = "Sede Este",
                            FechaRegistro = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            NombreCliente = "Paola Tao",
                            PlazoMeses = 24,
                            TasaInteres = 2m,
                            UsuarioId = 1,
                            ValorCredito = 12881963m
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CedulaCliente = "1000000010",
                            ComercialNombre = "Sede Oeste",
                            FechaRegistro = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            NombreCliente = "Wendy Moscoso",
                            PlazoMeses = 40,
                            TasaInteres = 2m,
                            UsuarioId = 1,
                            ValorCredito = 13484682m
                        });
                });

            modelBuilder.Entity("RegistroCreditos.Api.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "test@empresa.com",
                            Nombre = "Usuario de Pruebas",
                            PasswordHash = "$2a$11$g6.B3h9gR18B.E.X8bZ31ui/5jA1p49G1eS0Fw8m7.N885D5K67O6"
                        });
                });

            modelBuilder.Entity("RegistroCreditos.Api.Models.Credito", b =>
                {
                    b.HasOne("RegistroCreditos.Api.Models.Usuario", "Usuario")
                        .WithMany("Creditos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("RegistroCreditos.Api.Models.Usuario", b =>
                {
                    b.Navigation("Creditos");
                });
#pragma warning restore 612, 618
        }
    }
}
